version: 2
jobs:
  build:
    environment:
      IMAGE_NAME: s3848845/node-hello
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t node-hello .
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master