# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  node: circleci/node@4.7.0

jobs:
  build:
    docker:
      # replace with your preferred image
      - image: cimg/base:node-hello
    steps:
      - run: npm start