# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  node: circleci/node@4.1

jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: node-hello
    steps:
      - node/install
workflows:
  example-workflow:
    jobs:
      - example-job